# Generated by Django 4.0.1 on 2022-01-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_events_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events',
        ),
    ]
