# Generated by Django 4.0.1 on 2022-01-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0003_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('host_email', models.EmailField(max_length=200)),
                ('host_pw', models.CharField(max_length=10)),
                ('deadline_date', models.DateField()),
            ],
        ),
    ]
